// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using devGamesAPI.Data;

#nullable disable

namespace devGamesAPI.Migrations
{
    [DbContext(typeof(DevGamesContext))]
    [Migration("20250205171207_users")]
    partial class Users : Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Existing code...
        }
    }
}
